### ISSUE TITLE
Make translate_text correctly handle a single string.

### ISSUE THREAD

**Issue by verhovsky** [googleapis/python-translate#3]
You should either check for `str` and raise a `TypeError` or convert it to a list with one element (and return a string instead of a list) like you did in the v2 API. Right now if you pass a str, it'll be translated letter by letter

```python
from pathlib import Path

from google.cloud.translate import TranslationServiceClient
from google.oauth2 import service_account


CREDENTIALS_FILE = "creds.json"

_credentials = service_account.Credentials.from_service_account_file(CREDENTIALS_FILE)
PROJECT_ID = "projects/" + _credentials.project_id

result = TranslationServiceClient(credentials=_credentials).translate_text(
    "letter by letter",
    target_language_code="ru",
    source_language_code="en",
    mime_type="text/plain",
    parent=PROJECT_ID,
)

print(result.translations[0].translated_text)
print([translation.translated_text for translation in result.translations])
```

outputs

```text
L
['L', 'е', 'T', 'T', 'е', 'р', '\xa0', 'б', 'Y', '\xa0', 'L', 'е', 'T', 'T', 'е', 'р']
```

**Comment by czahedi** [comment]
@busunkim96 can you take a look at this again? If it's just that the generated client is being weird, maybe it has since been fixed?

**Comment by busunkim96** [comment]
The client expects you to pass a list. It looks like if you pass a string it treats it as a list of characters.

https://googleapis.dev/python/translation/latest/gapic/v3/api.html#google.cloud.translate_v3.TranslationServiceClient.translate_text

```py
client = translate_v3.TranslationServiceClient()

# TODO: Initialize `contents`:
contents = ["letter by letter"]

# TODO: Initialize `target_language_code`:
target_language_code = ''
parent = client.location_path('[PROJECT]', '[LOCATION]')

response = client.translate_text(contents, target_language_code, parent)
```

Since this is a generated client, I'm not sure how feasible it would be to change the behavior.

@software-dov Do you have any other thoughts?

**Comment by danoscarmike** [comment]
@software-dov how does the micro generator handle this? Same or will the migration fix this?

**Comment by software-dov** [comment]
Expository background: the microgenerator method surface changes slightly to take either fully constructed request objects (passed as dicts or first-class messages) or keyword-only flattened params.
E.g.
```python
text = ["this is a string", "this is another string", "the third string is the last"]
# Full request object
response = client.translate_text({"contents": contents, "target_language_code": target_language_code, "parent": parent})
# Flattened parameters for convenience
response = client.translate_text(contents=contents, target_language_code=target_language_code, parent=parent)
```

To answer the specific question: yes, the microgenerator surface will exhibit the same behavior. 'contents' is a repeated field, and the logic that constructs a full request expects an iterable. Purely due to quirks of python, a single string can be duck-typed into a list of strings. Much internet electricity has been spent debating whether this is a good idea, but it's the status quo.

My view is that this is a feature request that we shouldn't pursue. Consider an API method identical to this one where the 'contents' field stored some kind of custom message instead of strings; passing in a singleton would be a runtime error. Whether or not it should be allowable to pass in a singleton in that case is arguably the purview of the API owner. Handling the general case in the generator of allowing users to pass in a singleton when a method expects an iterable complicates generator logic and generator testing.

**Comment by danoscarmike** [comment]
Thanks @software-dov for the detailed explanation. Makes sense and agree it's not something to pursue at the generator level.

I guess we could investigate a handwritten helper/wrapper specific to this library method but I'm not sure it's worth it either.

**Comment by munkhuushmgl** [comment]
Feel free to reopen this, this issue is stale
